# Project 1: Explanatory Data Analysis & Data Presentation (Movies Dataset)

# Project Brief for Self-Coders

Here you´ll have the opportunity to code major parts of Project 1 on your own. If you need any help or inspiration, have a look at the Videos or the Jupyter Notebook with the full code. <br> <br>
Keep in mind that it´s all about __getting the right results/conclusions__. It´s not about finding the identical code. Things can be coded in many different ways. Even if you come to the same conclusions, it´s very unlikely that we have the very same code.

## Data Import and first Inspection

1. __Import__ the movies dataset from the CSV file "movies_complete.csv". __Inspect__ the data.

__Some additional information on Features/Columns__:

* **id:** The ID of the movie (clear/unique identifier).
* **title:** The Official Title of the movie.
* **tagline:** The tagline of the movie.
* **release_date:** Theatrical Release Date of the movie.
* **genres:** Genres associated with the movie.
* **belongs_to_collection:** Gives information on the movie series/franchise the particular film belongs to.
* **original_language:** The language in which the movie was originally shot in.
* **budget_musd:** The budget of the movie in million dollars.
* **revenue_musd:** The total revenue of the movie in million dollars.
* **production_companies:** Production companies involved with the making of the movie.
* **production_countries:** Countries where the movie was shot/produced in.
* **vote_count:** The number of votes by users, as counted by TMDB.
* **vote_average:** The average rating of the movie.
* **popularity:** The Popularity Score assigned by TMDB.
* **runtime:** The runtime of the movie in minutes.
* **overview:** A brief blurb of the movie.
* **spoken_languages:** Spoken languages in the film.
* **poster_path:** The URL of the poster image.
* **cast:** (Main) Actors appearing in the movie.
* **cast_size:** number of Actors appearing in the movie.
* **director:** Director of the movie.
* **crew_size:** Size of the film crew (incl. director, excl. actors).

In [1]:
import pandas as pd
import numpy as np
from IPython.core.pylabtools import figsize
from IPython.display import HTML
from wordcloud import WordCloud
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')

In [2]:
movies = pd.read_csv('movies_complete.csv', index_col='id')

In [3]:
# movies.budget_musd.fillna(0, inplace=True)
# movies.revenue_musd.fillna(0, inplace=True)
# movies

## The best and the worst movies...

2. __Filter__ the Dataset and __find the best/worst n Movies__ with the

- Highest Revenue
- Highest Budget
- Highest Profit (=Revenue - Budget)
- Lowest Profit (=Revenue - Budget)
- Highest Return on Investment (=Revenue / Budget) (only movies with Budget >= 10) 
- Lowest Return on Investment (=Revenue / Budget) (only movies with Budget >= 10)
- Highest number of Votes
- Highest Rating (only movies with 10 or more Ratings)
- Lowest Rating (only movies with 10 or more Ratings)
- Highest Popularity

__Define__ an appropriate __user-defined function__ to reuse code.

__Movies Top 5 - Highest Revenue__

In [4]:
movies.sort_values('revenue_musd', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
19995,Avatar,Enter the World of Pandora.,2009-12-10,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,Ingenious Film Partners|Twentieth Century Fox ...,United States of America|United Kingdom,...,7.2,185.070892,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron
140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15,Action|Adventure|Science Fiction|Fantasy,Star Wars Collection,en,245.0,2068.223624,Lucasfilm|Truenorth Productions|Bad Robot,United States of America,...,7.5,31.626013,136.0,Thirty years after defeating the Galactic Empi...,English,<img src='http://image.tmdb.org/t/p/w185//9rd0...,Daisy Ridley|John Boyega|Adam Driver|Harrison ...,84,113,J.J. Abrams
597,Titanic,Nothing on Earth could come between them.,1997-11-18,Drama|Romance|Thriller,NaN,en,200.0,1845.034188,Paramount Pictures|Twentieth Century Fox Film ...,United States of America,...,7.5,26.889070,194.0,"84 years later, a 101-year-old woman named Ros...",English|Français|Deutsch|svenska|Italiano|Pусский,<img src='http://image.tmdb.org/t/p/w185//9xjZ...,Kate Winslet|Leonardo DiCaprio|Frances Fisher|...,136,65,James Cameron
24428,The Avengers,Some assembly required.,2012-04-25,Science Fiction|Action|Adventure,The Avengers Collection,en,220.0,1519.557910,Paramount Pictures|Marvel Studios,United States of America,...,7.4,89.887648,143.0,When an unexpected enemy emerges and threatens...,English,<img src='http://image.tmdb.org/t/p/w185//RYMX...,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,115,147,Joss Whedon
135397,Jurassic World,The park is open.,2015-06-09,Action|Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,150.0,1513.528810,Universal Studios|Amblin Entertainment|Legenda...,United States of America,...,6.5,32.790475,124.0,Twenty-two years after the events of Jurassic ...,English,<img src='http://image.tmdb.org/t/p/w185//rhr4...,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,28,435,Colin Trevorrow

__Movies Top 5 - Highest Budget__

In [5]:
movies.sort_values('budget_musd', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
1865,Pirates of the Caribbean: On Stranger Tides,Live Forever Or Die Trying.,2011-05-14,Adventure|Action|Fantasy,Pirates of the Caribbean Collection,en,380.0,1045.713802,Walt Disney Pictures|Jerry Bruckheimer Films|M...,United States of America,...,6.4,27.887720,136.0,Captain Jack Sparrow crosses paths with a woma...,English|Español,<img src='http://image.tmdb.org/t/p/w185//keGf...,Johnny Depp|Penélope Cruz|Ian McShane|Kevin Mc...,36,39,Rob Marshall
285,Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.",2007-05-19,Adventure|Fantasy|Action,Pirates of the Caribbean Collection,en,300.0,961.000000,Walt Disney Pictures|Jerry Bruckheimer Films|S...,United States of America,...,6.9,31.363664,169.0,"Captain Barbossa, long believed to be dead, ha...",English,<img src='http://image.tmdb.org/t/p/w185//oVh3...,Johnny Depp|Orlando Bloom|Keira Knightley|Stel...,34,32,Gore Verbinski
99861,Avengers: Age of Ultron,A New Age Has Come.,2015-04-22,Action|Adventure|Science Fiction,The Avengers Collection,en,280.0,1405.403694,Marvel Studios|Prime Focus|Revolution Sun Studios,United States of America,...,7.3,37.379420,141.0,When Tony Stark tries to jumpstart a dormant p...,English,<img src='http://image.tmdb.org/t/p/w185//4ssD...,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,72,74,Joss Whedon
1452,Superman Returns,NaN,2006-06-28,Adventure|Fantasy|Action|Science Fiction,Superman Collection,en,270.0,391.081192,DC Comics|Legendary Pictures|Warner Bros.|Bad ...,United States of America,...,5.4,13.284712,154.0,Superman returns to discover his 5-year absenc...,English|Français|Deutsch,<img src='http://image.tmdb.org/t/p/w185//6ZYO...,Brandon Routh|Kevin Spacey|Kate Bosworth|James...,18,24,Bryan Singer
335988,Transformers: The Last Knight,"For one world to live, the other must die.",2017-06-21,Action|Science Fiction|Thriller|Adventure,Transformers Collection,en,260.0,604.942143,Paramount Pictures|Di Bonaventura Pictures|Ang...,United States of America,...,6.2,39.186819,149.0,"Autobots and Decepticons are at war, with huma...",English,<img src='http://image.tmdb.org/t/p/w185//s5HQ...,Mark Wahlberg|Josh Duhamel|Laura Haddock|Antho...,110,51,Michael Bay

__Movies Top 5 - Highest Profit__

In [6]:
movies['gross_profit_musd'] = movies['revenue_musd'] - movies['budget_musd']

In [7]:
column_order = ['title', 'tagline', 'release_date', 'genres', 'belongs_to_collection',
       'original_language', 'budget_musd', 'revenue_musd',
       'gross_profit_musd',
       'production_companies', 'production_countries', 'vote_count',
       'vote_average', 'popularity', 'runtime', 'overview', 'spoken_languages',
       'poster_path', 'cast', 'cast_size', 'crew_size', 'director']

In [8]:
movies =movies[column_order]

In [9]:
movies.loc[movies.budget_musd >= 5].sort_values('gross_profit_musd', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,production_companies,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
19995,Avatar,Enter the World of Pandora.,2009-12-10,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,2550.965087,Ingenious Film Partners|Twentieth Century Fox ...,...,7.2,185.070892,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron
140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15,Action|Adventure|Science Fiction|Fantasy,Star Wars Collection,en,245.0,2068.223624,1823.223624,Lucasfilm|Truenorth Productions|Bad Robot,...,7.5,31.626013,136.0,Thirty years after defeating the Galactic Empi...,English,<img src='http://image.tmdb.org/t/p/w185//9rd0...,Daisy Ridley|John Boyega|Adam Driver|Harrison ...,84,113,J.J. Abrams
597,Titanic,Nothing on Earth could come between them.,1997-11-18,Drama|Romance|Thriller,NaN,en,200.0,1845.034188,1645.034188,Paramount Pictures|Twentieth Century Fox Film ...,...,7.5,26.889070,194.0,"84 years later, a 101-year-old woman named Ros...",English|Français|Deutsch|svenska|Italiano|Pусский,<img src='http://image.tmdb.org/t/p/w185//9xjZ...,Kate Winslet|Leonardo DiCaprio|Frances Fisher|...,136,65,James Cameron
135397,Jurassic World,The park is open.,2015-06-09,Action|Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,150.0,1513.528810,1363.528810,Universal Studios|Amblin Entertainment|Legenda...,...,6.5,32.790475,124.0,Twenty-two years after the events of Jurassic ...,English,<img src='http://image.tmdb.org/t/p/w185//rhr4...,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,28,435,Colin Trevorrow
168259,Furious 7,Vengeance Hits Home,2015-04-01,Action,The Fast and the Furious Collection,en,190.0,1506.249360,1316.249360,Universal Pictures|Original Film|Fuji Televisi...,...,7.3,27.275687,137.0,Deckard Shaw seeks revenge against Dominic Tor...,English,<img src='http://image.tmdb.org/t/p/w185//d9jZ...,Vin Diesel|Paul Walker|Dwayne Johnson|Michelle...,52,98,James Wan

p__Movies Top 5 - Lowest Profit__

In [10]:
movies.loc[movies.budget_musd >= 5].sort_values('gross_profit_musd', ascending=True).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,production_companies,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
57201,The Lone Ranger,Never Take Off the Mask,2013-07-03,Action|Adventure|Western,NaN,en,255.000000,89.289910,-165.710090,Walt Disney Pictures|Jerry Bruckheimer Films|I...,...,5.9,12.729104,149.0,The Texas Rangers chase down a gang of outlaws...,English,<img src='http://image.tmdb.org/t/p/w185//b2je...,Johnny Depp|Armie Hammer|William Fichtner|Hele...,60,35,Gore Verbinski
10733,The Alamo,You will never forget,2004-04-07,Western|History|War,NaN,en,145.000000,25.819961,-119.180039,Imagine Entertainment|Touchstone Pictures,...,5.8,12.240901,137.0,Based on the 1836 standoff between a group of ...,English|Español,<img src='http://image.tmdb.org/t/p/w185//aZrW...,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,20,145,John Lee Hancock
50321,Mars Needs Moms,Mom needs a little space.,2011-03-09,Adventure|Animation|Family,NaN,en,150.000000,38.992758,-111.007242,Walt Disney Animation Studios,...,5.6,7.247170,88.0,"When Martians suddenly abduct his mom, mischie...",English,<img src='http://image.tmdb.org/t/p/w185//lOKq...,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,12,7,Simon Wells
339964,Valerian and the City of a Thousand Planets,NaN,2017-07-20,Adventure|Science Fiction|Action,NaN,en,197.471676,90.024292,-107.447384,EuropaCorp,...,6.7,15.262706,137.0,"In the 28th century, Valerian and Laureline ar...",Français|English,<img src='http://image.tmdb.org/t/p/w185//jfIp...,Dane DeHaan|Cara Delevingne|Clive Owen|Rihanna...,118,316,Luc Besson
1911,The 13th Warrior,Prey for the living.,1999-08-27,Adventure|Fantasy|Action,NaN,en,160.000000,61.698899,-98.301101,Touchstone Pictures,...,6.4,10.308026,102.0,"In AD 922, Arab courtier, Ahmad Ibn Fadlan acc...",English|Norsk,<img src='http://image.tmdb.org/t/p/w185//7pyh...,Antonio Banderas|Vladimir Kulich|Dennis Storhø...,19,17,John McTiernan

__Movies Top 5 - Highest ROI__

In [11]:
movies['ROI'] = movies['revenue_musd'] / movies['budget_musd']

In [12]:
column_order = ['title', 'tagline', 'release_date', 'genres', 'belongs_to_collection',
       'original_language', 'budget_musd', 'revenue_musd',
       'gross_profit_musd', 'ROI',
       'production_companies', 'production_countries', 'vote_count',
       'vote_average', 'popularity', 'runtime', 'overview', 'spoken_languages',
       'poster_path', 'cast', 'cast_size', 'crew_size', 'director']

In [13]:
movies =movies[column_order]

In [14]:
movies.loc[movies.budget_musd >= 5].sort_values('ROI', ascending=False)

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
601,E.T. the Extra-Terrestrial,He is afraid. He is alone. He is three million...,1982-04-03,Science Fiction|Adventure|Family|Fantasy,NaN,en,10.500000,792.965326,782.465326,75.520507,...,7.3,19.358546,115.0,After a gentle alien becomes stranded on Earth...,English,<img src='http://image.tmdb.org/t/p/w185//cBfk...,Henry Thomas|Drew Barrymore|Robert MacNaughton...,13,21,Steven Spielberg
8346,My Big Fat Greek Wedding,Love is here to stay... so is her family.,2002-02-22,Comedy|Drama|Romance,My Big Fat Greek Wedding Collection,en,5.000000,368.744044,363.744044,73.748809,...,6.2,6.719949,95.0,A young Greek woman falls in love with a non-G...,ελληνικά|English,<img src='http://image.tmdb.org/t/p/w185//3TB2...,Nia Vardalos|John Corbett|Lainie Kazan|Michael...,16,9,Joel Zwick
11,Star Wars,"A long time ago in a galaxy far, far away...",1977-05-25,Adventure|Action|Science Fiction,Star Wars Collection,en,11.000000,775.398007,764.398007,70.490728,...,8.1,42.149697,121.0,Princess Leia is captured and held hostage by ...,English,<img src='http://image.tmdb.org/t/p/w185//6FfC...,Mark Hamill|Harrison Ford|Carrie Fisher|Peter ...,106,20,George Lucas
578,Jaws,Don't go in the water.,1975-06-18,Horror|Thriller|Adventure,The Jaws Collection,en,7.000000,470.654000,463.654000,67.236286,...,7.5,19.726114,124.0,An insatiable great white shark terrorizes the...,English,<img src='http://image.tmdb.org/t/p/w185//s2xc...,Roy Scheider|Robert Shaw|Richard Dreyfuss|Lorr...,29,28,Steven Spielberg
9671,Crocodile Dundee,There's a little of him in all of us.,1986-09-26,Adventure|Comedy,Crocodile Dundee Collection,en,5.000000,328.203506,323.203506,65.640701,...,6.3,7.791212,97.0,When a New York reporter plucks crocodile hunt...,English,<img src='http://image.tmdb.org/t/p/w185//kiwO...,Paul Hogan|Linda Kozlowski|Mark Blum|David Gul...,10,10,Peter Faiman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59914,The Blonde with Bare Breasts,NaN,2010-07-21,Comedy|Drama,NaN,en,7.500000,NaN,NaN,NaN,...,4.0,0.882188,100.0,"Julian, 25, and Louis, 12, are two brothers wh...",Français,<img src='http://image.tmdb.org/t/p/w185//zBjp...,Vahina Giocante|Nicolas Duvauchelle|Steve Le R...,5,2,Manuel Pradal
407448,Detroit,It's time we knew,2017-07-28,Thriller|Crime|Drama|History,NaN,en,34.000000,NaN,NaN,NaN,...,7.3,9.797505,143.0,A police raid in Detroit in 1967 results in on...,English,<img src='http://image.tmdb.org/t/p/w185//7APL...,John Boyega|Will Poulter|Algee Smith|Jason Mit...,46,32,Kathryn Bigelow
277839,"Good Guys Go to Heaven, Bad Guys Go to Pattaya",NaN,2016-02-24,Comedy,NaN,fr,5.402000,NaN,NaN,NaN,...,5.3,5.613875,100.0,Franky and Krimo dream of leaving the grey gri...,Français,<img src='http://image.tmdb.org/t/p/w185//cfVB...,Ramzy Bedia|Malik Bentalha|Franck Gastambide|G...,19,10,Franck Gastambide
248705,The Visitors: Bastille Day,NaN,2016-03-23,Comedy,The Visitors Collection,fr,25.868826,NaN,NaN,NaN,...,4.0,7.294920,110.0,"Stuck in the corridors of time, Godefroy de Mo...",Français,<img src='http://image.tmdb.org/t/p/w185//kBlm...,Jean Reno|Christian Clavier|Franck Dubosc|Kari...,41,3,Jean-Marie Poiré
39164,House of the Long Shadows,NaN,1983-06-17,Horror|Comedy|Mystery,NaN,en,7.500000,NaN,NaN,NaN,...,6.1,1.185515,100.0,An American writer goes to a remote Welsh mano...,English,<img src='http://image.tmdb.org/t/p/w185//21ZG...,Vincent Price|Christopher Lee|Peter Cushing|De...,11,12,Pete Walker

__Movies Top 5 - Lowest ROI__

In [15]:
movies.loc[movies.budget_musd >= 5].sort_values('ROI', ascending=True)

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
14844,Chasing Liberty,How do you fall in love with the whole world w...,2004-01-09,Comedy|Romance,NaN,en,23.000000,0.000012,-22.999988,5.217391e-07,...,6.1,5.950792,111.0,"The President's daughter, unable to experience...",English|Français|עִבְרִית|Italiano|Español|Deu...,<img src='http://image.tmdb.org/t/p/w185//7qzv...,Mandy Moore|Stark Sands|Tony Jayawardena|Jerem...,11,26,Andy Cadiff
18475,The Cookout,"This summer, get your grill on!",2004-09-03,Comedy|Drama,NaN,en,16.000000,0.000012,-15.999988,7.500000e-07,...,4.6,1.758079,97.0,When Todd Anderson signs a $30 million deal wi...,English,<img src='http://image.tmdb.org/t/p/w185//eUVE...,Ja Rule|Tim Meadows|Jenifer Lewis|Jonathan Sil...,6,4,Lance Rivera
48781,Never Talk to Strangers,"In A World Where Love Isn't Always Safe, Trust...",1995-10-20,Thriller|Romance,NaN,en,6.400000,0.000006,-6.399994,9.375000e-07,...,4.7,7.506958,86.0,"Sarah Taylor, a police psychologist, meets a m...",English,<img src='http://image.tmdb.org/t/p/w185//IHZZ...,Rebecca De Mornay|Antonio Banderas|Dennis Mill...,7,3,Peter Hall
33927,Deadfall,...The ultimate con,1993-10-08,Crime|Drama|Thriller,NaN,en,10.000000,0.000018,-9.999982,1.800000e-06,...,3.1,1.145806,98.0,"After he accidentally kills his father, Mike, ...",English|Español,<img src='http://image.tmdb.org/t/p/w185//kgfv...,Michael Biehn|Sarah Trigger|Nicolas Cage|James...,12,3,Christopher Coppola
10944,In the Cut,Everything you know about desire is dead wrong.,2003-09-09,Mystery|Thriller,NaN,en,12.000000,0.000023,-11.999977,1.916667e-06,...,4.7,5.799628,119.0,Following the gruesome murder of a young woman...,English,<img src='http://image.tmdb.org/t/p/w185//lcor...,Meg Ryan|Mark Ruffalo|Jennifer Jason Leigh|Nic...,6,25,Jane Campion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59914,The Blonde with Bare Breasts,NaN,2010-07-21,Comedy|Drama,NaN,en,7.500000,NaN,NaN,NaN,...,4.0,0.882188,100.0,"Julian, 25, and Louis, 12, are two brothers wh...",Français,<img src='http://image.tmdb.org/t/p/w185//zBjp...,Vahina Giocante|Nicolas Duvauchelle|Steve Le R...,5,2,Manuel Pradal
407448,Detroit,It's time we knew,2017-07-28,Thriller|Crime|Drama|History,NaN,en,34.000000,NaN,NaN,NaN,...,7.3,9.797505,143.0,A police raid in Detroit in 1967 results in on...,English,<img src='http://image.tmdb.org/t/p/w185//7APL...,John Boyega|Will Poulter|Algee Smith|Jason Mit...,46,32,Kathryn Bigelow
277839,"Good Guys Go to Heaven, Bad Guys Go to Pattaya",NaN,2016-02-24,Comedy,NaN,fr,5.402000,NaN,NaN,NaN,...,5.3,5.613875,100.0,Franky and Krimo dream of leaving the grey gri...,Français,<img src='http://image.tmdb.org/t/p/w185//cfVB...,Ramzy Bedia|Malik Bentalha|Franck Gastambide|G...,19,10,Franck Gastambide
248705,The Visitors: Bastille Day,NaN,2016-03-23,Comedy,The Visitors Collection,fr,25.868826,NaN,NaN,NaN,...,4.0,7.294920,110.0,"Stuck in the corridors of time, Godefroy de Mo...",Français,<img src='http://image.tmdb.org/t/p/w185//kBlm...,Jean Reno|Christian Clavier|Franck Dubosc|Kari...,41,3,Jean-Marie Poiré
39164,House of the Long Shadows,NaN,1983-06-17,Horror|Comedy|Mystery,NaN,en,7.500000,NaN,NaN,NaN,...,6.1,1.185515,100.0,An American writer goes to a remote Welsh mano...,English,<img src='http://image.tmdb.org/t/p/w185//21ZG...,Vincent Price|Christopher Lee|Peter Cushing|De...,11,12,Pete Walker

__Movies Top 5 - Most Votes__

In [16]:
movies.loc[movies.budget_musd >= 5].sort_values('vote_count', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
27205,Inception,Your mind is the scene of the crime.,2010-07-14,Action|Thriller|Science Fiction|Mystery|Adventure,NaN,en,160.0,825.532764,665.532764,5.159580,...,8.1,29.108149,148.0,"Cobb, a skilled thief who commits corporate es...",English,<img src='http://image.tmdb.org/t/p/w185//9gk7...,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,29,18,Christopher Nolan
155,The Dark Knight,Why So Serious?,2008-07-16,Drama|Action|Crime|Thriller,The Dark Knight Collection,en,185.0,1004.558444,819.558444,5.430046,...,8.3,123.167259,152.0,Batman raises the stakes in his war on crime. ...,English|普通话,<img src='http://image.tmdb.org/t/p/w185//qJ2t...,Christian Bale|Michael Caine|Heath Ledger|Aaro...,134,81,Christopher Nolan
19995,Avatar,Enter the World of Pandora.,2009-12-10,Action|Adventure|Fantasy|Science Fiction,Avatar Collection,en,237.0,2787.965087,2550.965087,11.763566,...,7.2,185.070892,162.0,"In the 22nd century, a paraplegic Marine is di...",English|Español,<img src='http://image.tmdb.org/t/p/w185//btnl...,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,83,153,James Cameron
24428,The Avengers,Some assembly required.,2012-04-25,Science Fiction|Action|Adventure,The Avengers Collection,en,220.0,1519.557910,1299.557910,6.907081,...,7.4,89.887648,143.0,When an unexpected enemy emerges and threatens...,English,<img src='http://image.tmdb.org/t/p/w185//RYMX...,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,115,147,Joss Whedon
293660,Deadpool,Witness the beginning of a happy ending,2016-02-09,Action|Adventure|Comedy,Deadpool Collection,en,58.0,783.112979,725.112979,13.501948,...,7.4,187.860492,108.0,Deadpool tells the origin story of former Spec...,English,<img src='http://image.tmdb.org/t/p/w185//fSRb...,Ryan Reynolds|Morena Baccarin|Ed Skrein|T.J. M...,46,88,Tim Miller

__Movies Top 5 - Highest Rating__

In [17]:
movies.loc[movies.budget_musd >= 5].sort_values('vote_average', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
19404,Dilwale Dulhania Le Jayenge,Come... Fall In Love,1995-10-20,Comedy|Drama|Romance,NaN,hi,13.2,100.000000,86.800000,7.575758,...,9.1,34.457024,190.0,"Raj is a rich, carefree, happy-go-lucky second...",हिन्दी,<img src='http://image.tmdb.org/t/p/w185//2CAL...,Shah Rukh Khan|Kajol|Amrish Puri|Anupam Kher|S...,27,30,Aditya Chopra
153779,The Kingdom of Solomon,NaN,2010-10-06,Drama|History,NaN,en,5.0,NaN,NaN,NaN,...,9.0,1.027956,110.0,"Solomon, Prophet and the King, has asked God t...",فارسی|Türkçe,<img src='http://image.tmdb.org/t/p/w185//j24f...,NaN,0,2,Shahriar Bahrani
359364,Human,Accepting your true identity is accepting who ...,2015-09-12,Documentary,NaN,fr,13.0,NaN,NaN,NaN,...,8.6,3.845853,263.0,A combination of first-person stories and excl...,Pусский|ελληνικά|English|Español|Français|Ital...,<img src='http://image.tmdb.org/t/p/w185//vdZg...,Luis Cancu,1,8,Yann Arthus-Bertrand
88641,There Goes My Baby,NaN,1994-09-02,Drama|Comedy,NaN,en,10.5,0.123509,-10.376491,0.011763,...,8.5,0.377787,99.0,A group of high school seniors meets in the su...,English,<img src='http://image.tmdb.org/t/p/w185//7jXj...,Dermot Mulroney|Ricky Schroder|Kelli Williams|...,9,15,Floyd Mutrux
238,The Godfather,An offer you can't refuse.,1972-03-14,Drama|Crime,The Godfather Collection,en,6.0,245.066411,239.066411,40.844402,...,8.5,41.109264,175.0,"Spanning the years 1945 to 1955, a chronicle o...",English|Italiano|Latin,<img src='http://image.tmdb.org/t/p/w185//iVZ3...,Marlon Brando|Al Pacino|James Caan|Richard S. ...,58,42,Francis Ford Coppola

__Movies Top 5 - Lowest Rating__

In [18]:
movies.loc[movies.budget_musd >= 5].sort_values('vote_average', ascending=True).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
111744,Joe and Max,NaN,2002-03-03,Drama|TV Movie,NaN,en,8.0,NaN,NaN,NaN,...,0.0,1.669115,109.0,True story of boxers Joe Louis and Max Schmeli...,English|Deutsch|Italiano,<img src='http://image.tmdb.org/t/p/w185//1Ver...,Leonard Roberts|Til Schweiger|Peta Wilson|Rich...,11,2,Steve James
63898,Antidur,NaN,2007-09-06,Action|Comedy|Crime|Foreign,NaN,ru,5.0,1.41300,-3.58700,0.282600,...,1.0,0.039793,91.0,Failing to complete an important assignment wi...,Pусский,<img src='http://image.tmdb.org/t/p/w185//f5XO...,Vladimir Turchinsky|Dmitriy Dyuzhev|Tatyana Do...,4,1,Vladimir Shchegolkov
220669,Королёв,NaN,2007-10-29,Drama,NaN,ru,6.0,0.03100,-5.96900,0.005167,...,1.0,0.292296,NaN,NaN,NaN,<img src='http://image.tmdb.org/t/p/w185//mIYS...,Sergei Astahov,1,2,Yuriy Kara
42078,Elf Bowling the Movie,NaN,2007-10-02,Animation|Comedy|Fantasy,NaN,en,6.5,NaN,NaN,NaN,...,2.0,0.648653,82.0,So you think you know the real story behind Sa...,English,<img src='http://image.tmdb.org/t/p/w185//oFcH...,Joe Alaskey|Sean Hart|Tom Kenny,3,2,Rex Piano
272610,Black Rose,NaN,2014-04-17,Drama|Crime|Action,NaN,en,7.0,0.85545,-6.14455,0.122207,...,2.0,2.482771,83.0,A Russian Police Major is enlisted by the LAPD...,English|Pусский,<img src='http://image.tmdb.org/t/p/w185//zvyR...,Alexander Nevsky|Kristanna Loken|Adrian Paul|R...,9,8,Alexander Nevsky

__Movies Top 5 - Most Popular__

In [19]:
movies.loc[movies.budget_musd >= 5].sort_values('popularity', ascending=False).head()

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
211672,Minions,"Before Gru, they had a history of bad bosses",2015-06-17,Family|Animation|Adventure|Comedy,Despicable Me Collection,en,74.0,1156.730962,1082.730962,15.631499,...,6.4,547.488298,91.0,"Minions Stuart, Kevin and Bob are recruited by...",English,<img src='http://image.tmdb.org/t/p/w185//tMaG...,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,17,12,Kyle Balda
297762,Wonder Woman,Power. Grace. Wisdom. Wonder.,2017-05-30,Action|Adventure|Fantasy,Wonder Woman Collection,en,149.0,820.580447,671.580447,5.507251,...,7.2,294.337037,141.0,An Amazon princess comes to the world of Man t...,Deutsch|English,<img src='http://image.tmdb.org/t/p/w185//gfJG...,Gal Gadot|Chris Pine|Robin Wright|Danny Huston...,106,195,Patty Jenkins
321612,Beauty and the Beast,Be our guest.,2017-03-16,Family|Fantasy|Romance,NaN,en,160.0,1262.886337,1102.886337,7.893040,...,6.8,287.253654,129.0,A live-action adaptation of Disney's version o...,English,<img src='http://image.tmdb.org/t/p/w185//tWqi...,Emma Watson|Dan Stevens|Luke Evans|Kevin Kline...,156,115,Bill Condon
339403,Baby Driver,All you need is one killer track.,2017-06-28,Action|Crime,NaN,en,34.0,224.511319,190.511319,6.603274,...,7.2,228.032744,113.0,After being coerced into working for a crime b...,English,<img src='http://image.tmdb.org/t/p/w185//rmnQ...,Ansel Elgort|Lily James|Kevin Spacey|Jamie Fox...,56,183,Edgar Wright
177572,Big Hero 6,From the creators of Wreck-it Ralph and Frozen,2014-10-24,Adventure|Family|Animation|Action|Comedy,NaN,en,165.0,652.105443,487.105443,3.952154,...,7.8,213.849907,102.0,The special bond that develops between plus-si...,English,<img src='http://image.tmdb.org/t/p/w185//xozr...,Scott Adsit|Ryan Potter|Daniel Henney|T.J. Mil...,46,39,Chris Williams

## Find your next Movie

3. __Filter__ the Dataset for movies that meet the following conditions:

__Search 1: Science Fiction Action Movie with Bruce Willis (sorted from high to low Rating)__

__Search 2: Movies with Uma Thurman and directed by Quentin Tarantino (sorted from short to long runtime)__

__Search 3: Most Successful Pixar Studio Movies between 2010 and 2015 (sorted from high to low Revenue)__

__Search 4: Action or Thriller Movie with original language English and minimum Rating of 7.5 (most recent movies first)__

In [20]:
filter_genres = movies.genres.str.contains("Science Fiction") & movies.genres.str.contains("Action")
filter_actor = movies.cast.str.contains("Bruce Willis")
filtered_movies = movies[filter_genres & filter_actor]
filtered_movies.sort_values('vote_average', ascending=False)

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
18,The Fifth Element,There is no future without it.,1997-05-07,Adventure|Fantasy|Action|Thriller|Science Fiction,NaN,en,90.0,263.920180,173.920180,2.932446,...,7.3,24.305260,126.0,"In 2257, a taxi driver is unintentionally give...",English|svenska|Deutsch,<img src='http://image.tmdb.org/t/p/w185//fPtl...,Bruce Willis|Gary Oldman|Ian Holm|Milla Jovovi...,114,134,Luc Besson
59967,Looper,"Hunted By Your Future, Haunted By Your Past",2012-09-26,Action|Thriller|Science Fiction,NaN,en,30.0,47.042000,17.042000,1.568067,...,6.6,12.727269,118.0,"In the futuristic action thriller Looper, time...",English,<img src='http://image.tmdb.org/t/p/w185//sNjL...,Joseph Gordon-Levitt|Bruce Willis|Emily Blunt|...,34,42,Rian Johnson
95,Armageddon,The Earth's Darkest Day Will Be Man's Finest Hour,1998-07-01,Action|Thriller|Science Fiction|Adventure,NaN,en,140.0,553.799566,413.799566,3.955711,...,6.5,13.235112,151.0,When an asteroid threatens to collide with Ear...,English|Pусский,<img src='http://image.tmdb.org/t/p/w185//fMtO...,Bruce Willis|Billy Bob Thornton|Ben Affleck|Li...,67,108,Michael Bay
19959,Surrogates,How do you save humanity when the only thing t...,2009-09-24,Action|Science Fiction|Thriller,NaN,en,80.0,122.444772,42.444772,1.530560,...,5.9,16.211937,89.0,Set in a futuristic world where humans live in...,English|Français,<img src='http://image.tmdb.org/t/p/w185//v3Z0...,Bruce Willis|Radha Mitchell|Rosamund Pike|Jame...,44,25,Jonathan Mostow
72559,G.I. Joe: Retaliation,NaN,2013-03-26,Adventure|Action|Science Fiction|Thriller,G.I. Joe (Live-Action) Collection,en,130.0,371.876278,241.876278,2.860587,...,5.4,10.560608,110.0,"Framed for crimes against the country, the G.I...",English,<img src='http://image.tmdb.org/t/p/w185//3rWI...,Dwayne Johnson|D.J. Cotrona|Adrianne Palicki|B...,20,28,Jon M. Chu
307663,Vice,Where the future is your past.,2015-01-16,Thriller|Science Fiction|Action|Adventure,NaN,en,10.0,NaN,NaN,NaN,...,4.1,19.236571,96.0,Julian Michaels has designed the ultimate reso...,English,<img src='http://image.tmdb.org/t/p/w185//nPqN...,Ambyr Childers|Thomas Jane|Bryan Greenberg|Bru...,51,56,Brian A Miller

In [21]:
filter_director = movies.director.str.contains("Quentin Tarantino")
filter_actor = movies.cast.str.contains("Uma Thurman")
filtered_movies = movies[filter_director & filter_actor]
filtered_movies.sort_values('runtime', ascending=False)

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
680,Pulp Fiction,Just because you are a character doesn't mean ...,1994-09-10,Thriller|Crime,NaN,en,8.0,213.928762,205.928762,26.741095,...,8.3,140.950236,154.0,"A burger-loving hit man, his philosophical par...",English|Español|Français,<img src='http://image.tmdb.org/t/p/w185//d5iI...,John Travolta|Samuel L. Jackson|Uma Thurman|Br...,54,87,Quentin Tarantino
393,Kill Bill: Vol. 2,The bride is back for the final cut.,2004-04-16,Action|Crime|Thriller,Kill Bill Collection,en,30.0,152.159461,122.159461,5.071982,...,7.7,21.533072,136.0,The Bride unwaveringly continues on her roarin...,English|普通话|Español|广州话 / 廣州話,<img src='http://image.tmdb.org/t/p/w185//2yhg...,Uma Thurman|David Carradine|Daryl Hannah|Micha...,27,130,Quentin Tarantino
24,Kill Bill: Vol. 1,Go for the kill.,2003-10-10,Action|Crime,Kill Bill Collection,en,30.0,180.949000,150.949000,6.031633,...,7.7,25.261865,111.0,An assassin is shot at the altar by her ruthle...,English|日本語|Français,<img src='http://image.tmdb.org/t/p/w185//v7Ta...,Uma Thurman|Lucy Liu|Vivica A. Fox|Daryl Hanna...,36,161,Quentin Tarantino

In [22]:
filter_studio = movies.production_companies.str.contains("Pixar")
filter_date = movies.release_date.between('2010-01-01','2015-12-31')
filtered_movies = movies[filter_studio & filter_date].sort_values('revenue_musd', ascending=False)
filtered_movies

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
10193,Toy Story 3,No toy gets left behind.,2010-06-16,Animation|Family|Comedy,Toy Story Collection,en,200.0,1066.969703,866.969703,5.334849,...,7.6,16.966470,103.0,"Woody, Buzz, and the rest of Andy's toys haven...",English|Español,<img src='http://image.tmdb.org/t/p/w185//amY0...,Tom Hanks|Tim Allen|Ned Beatty|Joan Cusack|Mic...,45,38,Lee Unkrich
150540,Inside Out,Meet the little voices inside your head.,2015-06-09,Drama|Comedy|Animation|Family,NaN,en,175.0,857.611174,682.611174,4.900635,...,7.9,23.985587,94.0,"Growing up can be a bumpy road, and it's no ex...",English,<img src='http://image.tmdb.org/t/p/w185//lRHE...,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,65,50,Pete Docter
62211,Monsters University,School never looked this scary.,2013-06-20,Animation|Family,"Monsters, Inc. Collection",en,200.0,743.559607,543.559607,3.717798,...,7.0,16.267502,104.0,A look at the relationship between Mike and Su...,English,<img src='http://image.tmdb.org/t/p/w185//tyHH...,Billy Crystal|John Goodman|Steve Buscemi|Helen...,24,13,Dan Scanlon
49013,Cars 2,Ka-ciao!,2011-06-11,Animation|Family|Adventure|Comedy,Cars Collection,en,200.0,559.852396,359.852396,2.799262,...,5.8,13.693002,106.0,Star race car Lightning McQueen and his pal Ma...,English|日本語|Italiano|Français,<img src='http://image.tmdb.org/t/p/w185//okIz...,Owen Wilson|Larry the Cable Guy|Michael Caine|...,47,40,John Lasseter
62177,Brave,Change your fate.,2012-06-21,Animation|Adventure|Comedy|Family|Action|Fantasy,NaN,en,185.0,538.983207,353.983207,2.913423,...,6.7,15.876341,93.0,Brave is set in the mystical Scottish Highland...,English,<img src='http://image.tmdb.org/t/p/w185//8l0p...,Kelly Macdonald|Billy Connolly|Emma Thompson|J...,15,44,Brenda Chapman
105864,The Good Dinosaur,Little Arms With Big Attitude,2015-11-14,Adventure|Animation|Family,NaN,en,175.0,331.926147,156.926147,1.896721,...,6.6,12.319595,93.0,An epic journey into the world of dinosaurs wh...,English,<img src='http://image.tmdb.org/t/p/w185//8RSk...,Raymond Ochoa|Jack Bright|Jeffrey Wright|Franc...,19,11,Peter Sohn
40619,Day & Night,NaN,2010-06-17,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,7.6,6.345512,6.0,"When Day, a sunny fellow, encounters Night, a ...",NaN,<img src='http://image.tmdb.org/t/p/w185//eQ1Q...,Wayne Dyer,1,1,Teddy Newton
200481,The Blue Umbrella,NaN,2013-02-12,Animation|Romance,NaN,en,NaN,NaN,NaN,NaN,...,7.8,6.568023,7.0,It is just another evening commute until the r...,No Language,<img src='http://image.tmdb.org/t/p/w185//iSWV...,Sarah Jaffe,1,1,Saschka Unseld
213121,Toy Story of Terror!,One toy gets left behind!,2013-10-15,Animation|Comedy|Family,NaN,en,NaN,NaN,NaN,NaN,...,7.3,0.512025,22.0,What starts out as a fun road trip for the Toy...,English,<img src='http://image.tmdb.org/t/p/w185//aNDr...,Tom Hanks|Tim Allen|Kristen Schaal|Carl Weathe...,8,8,Angus MacLane
83564,La luna,A young boy discovers his family's most unusua...,2011-01-01,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,8.0,7.331398,7.0,A young boy comes of age in the most peculiar ...,English,<img src='http://image.tmdb.org/t/p/w185//iS6D...,Krista Sheffler|Tony Fucile|Phil Sheridan,3,9,Enrico Casarosa
77887,Hawaiian Vacation,NaN,2011-06-16,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,6.9,11.315849,6.0,The toys throw Ken and Barbie a Hawaiian vacat...,English,<img src='http://image.tmdb.org/t/p/w185//tByW...,Tim Allen|Jodi Benson|Blake Clark|Tom Hanks|Jo...,21,8,Gary Rydstrom
82424,Small Fry,NaN,2011-11-23,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,6.8,9.858179,7.0,A fast food restaurant mini variant of Buzz fo...,English,<img src='http://image.tmdb.org/t/p/w185//z096...,Lori Alan|Carlos Alazraqui|Tim Allen|Bob Berge...,20,6,Angus MacLane
130925,Partysaurus Rex,An Electro Sudsy Good Time!,2012-09-14,Animation|Comedy|Family|Fantasy,NaN,en,NaN,NaN,NaN,NaN,...,7.4,6.066171,7.0,When Rex finds himself left behind in the bath...,English,<img src='http://image.tmdb.org/t/p/w185//ylj9...,Tom Hanks|Tim Allen|Wallace Shawn|Corey Burton...,28,13,Mark A. Walsh
141423,The Legend of Mor'du,NaN,2012-01-01,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,5.9,3.785848,6.0,The witch from Pixar's Brave uses magical illu...,English,<img src='http://image.tmdb.org/t/p/w185//8FKR...,Julie Walters|Steve Purcell|Callum O'Neil,3,7,Brian Larsen
256835,Toy Story That Time Forgot,NaN,2014-12-02,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,6.8,8.609555,22.0,"During a post-Christmas play date, the gang fi...",English,<img src='http://image.tmdb.org/t/p/w185//jqQP...,Tom Hanks|Tim Allen|Joan Cusack|Kristen Schaal...,8,4,Steve Purcell
286192,Lava,NaN,2015-06-21,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,7.4,5.761878,7.0,The story follows the love story of two volcan...,English,<img src='http://image.tmdb.org/t/p/w185//blZS...,Napua Greig|Kuana Torres Kahele,2,19,James Ford Murphy
345637,Sanjay's Super Team,NaN,2015-11-25,Animation,NaN,en,NaN,NaN,NaN,NaN,...,6.9,4.335730,7.0,Sanjay's Super Team follows the daydream of a ...,English,<img src='http://image.tmdb.org/t/p/w185//mShc...,NaN,0,4,Sanjay Patel
145316,Air Mater,NaN,2011-08-04,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,5.8,8.844424,6.0,Mater's decision to fly lands him accidentally...,English,<img src='http://image.tmdb.org/t/p/w185//jDwg...,Larry the Cable Guy|Stacy Keach|Keith Ferguson...,12,4,Rob Gibbs
355338,Riley's First Date?,NaN,2015-11-03,Animation|Family,NaN,en,NaN,NaN,NaN,NaN,...,7.2,6.051285,5.0,"Riley, now 12, is hanging out at home with her...",English,<img src='http://image.tmdb.org/t/p/w185//pyry...,Amy Poehler|Phyllis Smith|Bill Hader|Lewis Bla...,20,4,Josh Cooley

In [23]:
filter_genres = movies.genres.str.contains("Action") & movies.genres.str.contains("Thriller")
filter_lang = movies.original_language.str.contains("en")
filter_rating = movies.vote_average.between(7.5,10)
filtered_movies = movies[filter_genres & filter_lang & filter_rating].sort_values('release_date', ascending=False)
filtered_movies

,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,gross_profit_musd,ROI,...,vote_average,popularity,runtime,overview,spoken_languages,poster_path,cast,cast_size,crew_size,director
id,,,,,,,,,,,,,,,,,,,,,
374720,Dunkirk,The event that shaped our world,2017-07-19,Action|Drama|History|Thriller|War,NaN,en,100.00000,519.876949,419.876949,5.198769,...,7.5,30.938854,107.0,The miraculous evacuation of Allied soldiers f...,English|Français|Deutsch,<img src='http://image.tmdb.org/t/p/w185//ebSn...,Fionn Whitehead|Tom Glynn-Carney|Jack Lowden|H...,66,214,Christopher Nolan
109424,Captain Phillips,Out here survival is everything.,2013-10-10,Action|Drama|Thriller,NaN,en,55.00000,95.000000,40.000000,1.727273,...,7.6,13.776068,134.0,The true story of Captain Richard Phillips and...,English|Somali,<img src='http://image.tmdb.org/t/p/w185//gffn...,Tom Hanks|Catherine Keener|Max Martini|Chris M...,17,85,Paul Greengrass
49026,The Dark Knight Rises,The Legend Ends,2012-07-16,Action|Crime|Drama|Thriller,The Dark Knight Collection,en,250.00000,1084.939099,834.939099,4.339756,...,7.6,20.582580,165.0,Following the death of District Attorney Harve...,English,<img src='http://image.tmdb.org/t/p/w185//vzvK...,Christian Bale|Michael Caine|Gary Oldman|Anne ...,158,217,Christopher Nolan
107170,Ghost Recon: Alpha,NaN,2012-05-03,Action|Science Fiction|Thriller|War,NaN,en,NaN,NaN,NaN,NaN,...,7.5,3.036216,24.0,Ghost Recon: Alpha sees a team led by Ghost Le...,English,<img src='http://image.tmdb.org/t/p/w185//iCEF...,Radek Bruna|Mark Ivanir|Keith Gilmore|Pavel Le...,11,3,François Alaux
84690,Oxy-Morons,NaN,2011-10-02,Action|Thriller,NaN,en,3.50000,NaN,NaN,NaN,...,8.0,0.086584,111.0,It's an action-packed thriller that borders on...,English,<img src='http://image.tmdb.org/t/p/w185//5zXf...,Damien Di Paola|Johnny Hickey|Tim Sylvia|Patty...,4,1,Johnny Hickey
27205,Inception,Your mind is the scene of the crime.,2010-07-14,Action|Thriller|Science Fiction|Mystery|Adventure,NaN,en,160.00000,825.532764,665.532764,5.159580,...,8.1,29.108149,148.0,"Cobb, a skilled thief who commits corporate es...",English,<img src='http://image.tmdb.org/t/p/w185//9gk7...,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,29,18,Christopher Nolan
16869,Inglourious Basterds,Once upon a time in Nazi occupied France...,2009-08-18,Drama|Action|Thriller|War,NaN,en,70.00000,319.131050,249.131050,4.559015,...,7.9,16.895640,153.0,"In Nazi-occupied France during World War II, a...",Deutsch|English|Français|Italiano,<img src='http://image.tmdb.org/t/p/w185//7sfb...,Brad Pitt|Mélanie Laurent|Christoph Waltz|Eli ...,71,42,Quentin Tarantino
176241,Prison Break: The Final Break,Prepare yourself for the truth,2009-05-26,Action|Drama|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.5,6.526913,89.0,The movie covers the events which occurred in ...,English,<img src='http://image.tmdb.org/t/p/w185//h1QR...,Wentworth Miller|Sarah Wayne Callies|Dominic P...,7,3,Brad Turner
155,The Dark Knight,Why So Serious?,2008-07-16,Drama|Action|Crime|Thriller,The Dark Knight Collection,en,185.00000,1004.558444,819.558444,5.430046,...,8.3,123.167259,152.0,Batman raises the stakes in his war on crime. ...,English|普通话,<img src='http://image.tmdb.org/t/p/w185//qJ2t...,Christian Bale|Michael Caine|Heath Ledger|Aaro...,134,81,Christopher Nolan
32534,I Am So Proud of You,NaN,2008-01-01,Animation|Action|Thriller|Science Fiction,NaN,en,NaN,NaN,NaN,NaN,...,8.3,0.472132,22.0,"Dark shadows are cast over Bill's recovery, in...",NaN,<img src='http://image.tmdb.org/t/p/w185//rLOR...,Don Hertzfeldt,1,2,Don Hertzfeldt
27442,Senseless,NaN,2008-01-01,Action|Adventure|Drama|Foreign|Horror|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.5,0.467144,87.0,Elliott Gast (Jason Behr) is quickly climbing ...,English,<img src='http://image.tmdb.org/t/p/w185//5Cz5...,Jason Behr|Emma Catherwood|Joe Ferrara|Sean O'...,4,2,Simon Hynd
15156,Illegal Tender,NaN,2007-08-24,Drama|Action|Thriller|Crime,NaN,en,NaN,3.106835,NaN,NaN,...,7.6,1.689926,108.0,After the gangsters who killed his father come...,English,<img src='http://image.tmdb.org/t/p/w185//5mbW...,Rick Gonzalez|Wanda De Jesus|Dania Ramirez|Del...,8,4,Franc. Reyes
752,V for Vendetta,People should not be afraid of their governmen...,2006-03-15,Action|Thriller|Fantasy,NaN,en,54.00000,132.511035,78.511035,2.453908,...,7.7,20.214422,132.0,In a world in which Great Britain has become a...,English,<img src='http://image.tmdb.org/t/p/w185//2ySX...,Natalie Portman|Hugo Weaving|Stephen Rea|Steph...,77,194,James McTeigue
33460,Sehar,NaN,2005-07-29,Action|Foreign|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.7,0.463688,NaN,"Ajay Kumar (Warsi) is the newly appointed, hon...",हिन्दी,<img src='http://image.tmdb.org/t/p/w185//mfLI...,Arshad Warsi|Sushant Singh|Pankaj Kapur|Mahima...,11,5,Kabeer Kaushik
393,Kill Bill: Vol. 2,The bride is back for the final cut.,2004-04-16,Action|Crime|Thriller,Kill Bill Collection,en,30.00000,152.159461,122.159461,5.071982,...,7.7,21.533072,136.0,The Bride unwaveringly continues on her roarin...,English|普通话|Español|广州话 / 廣州話,<img src='http://image.tmdb.org/t/p/w185//2yhg...,Uma Thurman|David Carradine|Daryl Hannah|Micha...,27,130,Quentin Tarantino
13905,Farscape: The Peacekeeper Wars,"John Crichton may not have started the war, bu...",2004-01-01,Action|Comedy|Romance|Science Fiction|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.5,5.715534,182.0,Sixty days on and Rygel is retrieving pieces o...,English,<img src='http://image.tmdb.org/t/p/w185//wg2i...,Claudia Black|Ben Browder|Anthony Simcoe|Gigi ...,19,45,Brian Henson
53670,Say Nothing,Think Fatal Attraction … in reverse!,2001-08-01,Action|Drama|Mystery|Romance|Science Fiction|T...,NaN,en,NaN,NaN,NaN,NaN,...,9.0,0.229743,94.0,Housewife Grace Needham (Nastassja Kinski) has...,English|Español,<img src='http://image.tmdb.org/t/p/w185//nUH2...,William Baldwin|Hart Bochner|Nastassja Kinski|...,5,1,Allan Moyle
949,Heat,A Los Angeles Crime Saga,1995-12-15,Action|Crime|Drama|Thriller,NaN,en,60.00000,187.436818,127.436818,3.123947,...,7.7,17.924927,170.0,"Obsessive master thief, Neil McCauley leads a ...",English|Español,<img src='http://image.tmdb.org/t/p/w185//lbf2...,Al Pacino|Robert De Niro|Val Kilmer|Jon Voight...,65,71,Michael Mann
29231,The Immortals,It was a chance of a lifetime. If they lived t...,1995-10-05,Action|Crime|Drama|Thriller,NaN,en,0.00005,0.000083,0.000033,1.660000,...,7.8,0.825042,98.0,An elaborate heist unites 8 strangers in a sim...,English|Français|Pусский,<img src='http://image.tmdb.org/t/p/w185//2af4...,Eric Roberts|Joe Pantoliano|Tia Carrere|Tony C...,9,11,Brian Grant
288173,Hostile Intentions,A night of adventure becomes one woman's despe...,1995-01-01,Thriller|Action|Drama,NaN,en,NaN,NaN,NaN,NaN,...,8.0,0.062388,90.0,A weekend of fun becomes a fight for survival ...,Español|English,<img src='http://image.tmdb.org/t/p/w185//mYcz...,Tia Carrere|Rigg Kennedy|Lisa Dean Ryan|Tricia...,5,2,Catherine Cyran
6075,Carlito's Way,He's got a good future if he can live past nex...,1993-11-10,Action|Crime|Drama|Thriller,NaN,en,30.00000,36.516012,6.516012,1.217200,...,7.7,8.698509,144.0,"A Puerto-Rican ex-con, just released from pris...",English|Español,<img src='http://image.tmdb.org/t/p/w185//hkQa...,Al Pacino|Sean Penn|Penelope Ann Miller|John L...,63,40,Brian De Palma
319,True Romance,"Stealing, Cheating, Killing. Who said romance ...",1993-09-09,Action|Thriller|Crime|Romance,NaN,en,12.50000,12.281551,-0.218449,0.982524,...,7.5,17.189328,120.0,"Clarence marries hooker Alabama, steals cocain...",English|Italiano,<img src='http://image.tmdb.org/t/p/w185//AqlP...,Christian Slater|Patricia Arquette|Michael Rap...,40,39,Tony Scott
9702,Bound by Honor,An epic story of three brothers. Bound by bloo...,1993-02-05,Action|Crime|Drama|Thriller,NaN,en,35.00000,NaN,NaN,NaN,...,7.7,6.398031,180.0,Based on the true life experiences of poet Jim...,English,<img src='http://image.tmdb.org/t/p/w185//ykkG...,Дэмиан Чапа|Jesse Borrego|Benjamin Bratt|Enriq...,15,16,Taylor Hackford
280,Terminator 2: Judgment Day,It's nothing personal.,1991-07-01,Action|Thriller|Science Fiction,The Terminator Collection,en,100.00000,520.000000,420.000000,5.200000,...,7.7,22.661695,137.0,Nearly 10 years have passed since Sarah Connor...,English|Español,<img src='http://image.tmdb.org/t/p/w185//5M0j...,Arnold Schwarzenegger|Linda Hamilton|Robert Pa...,42,54,James Cameron
31942,Midnight Ride,"Somewhere round the next bend, lies the road t...",1990-01-01,Thriller|Action|Horror,NaN,en,NaN,NaN,NaN,NaN,...,8.0,0.766401,93.0,"A house wife just left her cop husband, when s...",English,<img src='http://image.tmdb.org/t/p/w185//8lQG...,Michael Dudikoff|Mark Hamill|Robert Mitchum|Sa...,8,4,Bob Bralver
562,Die Hard,40 Stories. Twelve Terrorists. One Cop.,1988-07-15,Action|Thriller,Die Hard Collection,en,28.00000,140.767956,112.767956,5.027427,...,7.5,16.640522,131.0,"NYPD cop, John McClane's plan to reconcile wit...",English|Deutsch|Italiano,<img src='http://image.tmdb.org/t/p/w185//aJCp...,Bruce Willis|Alan Rickman|Alexander Godunov|Bo...,47,75,John McTiernan
679,Aliens,This Time It's War,1986-07-18,Horror|Action|Thriller|Science Fiction,Alien Collection,en,18.50000,183.316455,164.816455,9.908998,...,7.7,21.761179,137.0,When Ripley's lifepod is found by a salvage cr...,English,<img src='http://image.tmdb.org/t/p/w185//xwdP...,Sigourney Weaver|Michael Biehn|James Remar|Pau...,26,38,James Cameron
111,Scarface,The world is yours...,1983-12-08,Action|Crime|Drama|Thriller,NaN,en,25.00000,65.884703,40.884703,2.635388,...,8.0,11.299673,170.0,After getting a green card in exchange for ass...,English|Español,<img src='http://image.tmdb.org/t/p/w185//j5hI...,Al Pacino|Steven Bauer|Michelle Pfeiffer|Mary ...,63,42,Brian De Palma
348,Alien,In space no one can hear you scream.,1979-05-25,Horror|Action|Thriller|Science Fiction,Alien Collection,en,11.00000,104.931801,93.931801,9.539255,...,7.9,23.377420,117.0,"During its return to the earth, commercial spa...",English|Español,<img src='http://image.tmdb.org/t/p/w185//vfrQ...,Tom Skerritt|Sigourney Weaver|Veronica Cartwri...,10,30,Ridley Scott
81772,The Concorde Affair,NaN,1979-03-23,Action|Crime|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.5,0.816083,96.0,A reporter tries to stop the crash of an aircr...,Italiano,<img src='http://image.tmdb.org/t/p/w185//WOsg...,James Franciscus|Mimsy Farmer|Venantino Venant...,38,6,Ruggero Deodato
38985,Sorcerer,WANTED. Four men willing to drive a cargo of d...,1977-06-24,Action|Thriller|Adventure,NaN,en,22.00000,12.000000,-10.000000,0.545455,...,7.5,13.966833,121.0,Four exiled international criminals on the run...,English|Français|Deutsch|Español,<img src='http://image.tmdb.org/t/p/w185//xDQW...,Roy Scheider|Bruno Cremer|Francisco Rabal|Amid...,14,9,William Friedkin
8333,The Taking of Pelham One Two Three,We are going to kill one passenger a minute un...,1974-10-02,Action|Adventure|Crime|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.6,7.762833,104.0,"In New York, armed men hijack a subway car and...",English,<img src='http://image.tmdb.org/t/p/w185//vNhy...,Walter Matthau|Robert Shaw|Martin Balsam|Hécto...,19,27,Joseph Sargent
86600,The Internecine Project,Who will be alive when the hands stop?,1974-07-24,Action|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.8,1.672384,89.0,Former secret agent Robert Elliot (Coburn) wil...,Deutsch,<img src='http://image.tmdb.org/t/p/w185//HRX4...,James Coburn|Lee Grant|Harry Andrews|Ian Hendr...,9,9,Ken Hughes
119364,The Take,Meet the brother with a badge... on the take!,1974-05-01,Action|Thriller|Documentary,NaN,en,NaN,NaN,NaN,NaN,...,8.0,0.645963,91.0,A policeman in New Mexico takes payoff money b...,English,<img src='http://image.tmdb.org/t/p/w185//mrAB...,Billy Dee Williams|Eddie Albert|Frankie Avalon...,11,4,Robert Hartford-Davis
42329,The Valley of Gwangi,Cowboys Battle Monsters in the Lost World of F...,1969-07-24,Action|Fantasy|Science Fiction|Thriller|Western,NaN,en,NaN,NaN,NaN,NaN,...,7.5,2.082918,96.0,A turn of the century wild west show strugglin...,English,<img src='http://image.tmdb.org/t/p/w185//5RP7...,James Franciscus|Gila Golan|Richard Carlson|La...,9,9,Jim O'Connolly
247,The Killing,"...Like No Other Picture Since ""Scarface"" and ...",1956-05-08,Drama|Action|Thriller|Crime,NaN,en,0.32000,NaN,NaN,NaN,...,7.7,10.223264,85.0,The Killing was Stanley Kubrick’s first film w...,English,<img src='http://image.tmdb.org/t/p/w185//8fT4...,Sterling Hayden|Coleen Gray|Vince Edwards|Jay ...,37,24,Stanley Kubrick
16958,The Asphalt Jungle,The City Under the City,1950-05-22,Action|Crime|Drama|Thriller,NaN,en,NaN,NaN,NaN,NaN,...,7.5,12.865590,112.0,"Recently paroled from prison, legendary burgla...",English,<img src='http://image.tmdb.org/t/p/w185//kIkP...,Sterling Hayden|Louis Calhern|Jean Hagen|James...,15,16,John Huston
22584,To Have and Have Not,TALK ABOUT T.N.T.! THIS is IT!,1944-10-11,War|Action|Adventure|Drama|Romance|Thriller,NaN,en,NaN,3.650000,NaN,NaN,...,7.6,10.003167,100.0,A Martinique charter boat skipper gets mixed u...,English|Français,<img src='http://image.tmdb.org/t/p/w185//5MLI...,Humphrey Bogart|Walter Brennan|Lauren Bacall|D...,35,38,Howard Hawks
877,Scarface,The rise and fall of a power hungry mobster.,1932-04-09,Action|Adventure|Crime|Drama|Thriller,NaN,en,NaN,0.600000,NaN,NaN,...,7.5,4.854436,90.0,"Big Louis Costillo, last of the old-style gang...",English|Italiano,<img src='http://image.tmdb.org/t/p/w185//bnFj...,Paul Muni|Ann Dvorak|Karen Morley|Osgood Perki...,41,22,Howard Hawks

In [24]:
title = " ".join(movies['title'].dropna())
overview = " ".join(movies['overview'].dropna())
tagline = " ".join(movies['tagline'].dropna())

In [25]:
# title_wordcloud = WordCloud(background_color="black", height=2000, width=4000, max_words=200).generate(title)
# plt.figure(figsize=(16, 8))
# plt.imshow(title_wordcloud, interpolation="bilinear")
# plt.axis("off")
# plt.show()

In [26]:
# tagline_wordcloud = WordCloud(background_color="black", height=2000, width=4000, max_words=200).generate(tagline)
# plt.figure(figsize=(16, 8))
# plt.imshow(tagline_wordcloud, interpolation="bilinear")
# plt.axis("off")
# plt.show()

In [27]:
# overview_wordcloud = WordCloud(background_color="black", height=2000, width=4000, max_words=200).generate(overview)
# plt.figure(figsize=(16, 8))
# plt.imshow(overview_wordcloud, interpolation="bilinear")
# plt.axis("off")
# plt.show()

||## Are Franchises more successful?

4. __Analyze__ the Dataset and __find out whether Franchises (Movies that belong to a collection) are more successful than stand-alone movies__ in terms of:

- mean revenue
- median Return on Investment
- mean budget raised
- mean popularity
- mean rating

hint: use groupby()

__Franchise vs. Stand-alone: Average Revenue__

In [ ]:
movies['franchise'] = movies.belongs_to_collection.notna()

In [30]:
movies.franchise.value_counts()

franchise
False    40228
True      4463
Name: count, dtype: int64

In [ ]:
movies.groupby('franchise').median(numeric_only=True)

In [32]:
movies.groupby('franchise').agg({'budget_musd': np.mean, "revenue_musd": np.mean, "vote_count": np.mean, "popularity": np.mean, "ROI": np.median, "vote_count": np.mean})

C:\Users\alexb\AppData\Local\Temp\ipykernel_23856\1283429668.py:1: FutureWarning: The provided callable <function mean at 0x000001D45EE0D1C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  movies.groupby('franchise').agg({'budget_musd': np.mean, "revenue_musd": np.mean, "vote_count": np.mean, "popularity": np.mean, "ROI": np.median, "vote_count": np.mean})
C:\Users\alexb\AppData\Local\Temp\ipykernel_23856\1283429668.py:1: FutureWarning: The provided callable <function median at 0x000001D45EF6FA60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  movies.groupby('franchise').agg({'budget_musd': np.mean, "revenue_musd": np.mean, "vote_count": np.mean, "popularity": np.mean, "ROI": np.median, "vote_count": np.mean})

           budget_musd  revenue_musd  vote_count  popularity       ROI
franchise
False        18.047741     44.742814   78.289550    2.592726  1.619699
True         38.319847    165.708193  412.387856    6.245051  3.709195

}__Franchise vs. Stand-alone: Return on Investment / Profitability (median)__

__Franchise vs. Stand-alone: Average Budget__

__Franchise vs. Stand-alone: Average Popularity__

__Franchise vs. Stand-alone: Average Rating__

## Most Successful Franchises

5. __Find__ the __most successful Franchises__ in terms of

- __total number of movies__
- __total & mean budget__
- __total & mean revenue__
- __mean rating__

In [ ]:
movies.belongs_to_collection.value_counts()

In [ ]:
franchises = movies.groupby('belongs_to_collection').agg({"title": "count", "budget_musd": ["sum", "mean"], "revenue_musd": ["sum", "mean"], "vote_average": "mean", "ROI": "median", "vote_count": "mean"})
franchises

In [46]:
franchises.nlargest(20, ("revenue_musd", "sum"))

                                    title budget_musd              \
                                    count         sum        mean
belongs_to_collection
Harry Potter Collection                 8     1280.00  160.000000
Star Wars Collection                    8      854.35  106.793750
James Bond Collection                  26     1539.65   59.217308
The Fast and the Furious Collection     8     1009.00  126.125000
Pirates of the Caribbean Collection     5     1250.00  250.000000
Transformers Collection                 5      965.00  193.000000
Despicable Me Collection                6      299.00   74.750000
The Twilight Collection                 5      385.00   77.000000
Ice Age Collection                      5      429.00   85.800000
Jurassic Park Collection                4      379.00   94.750000
Shrek Collection                        5      535.00  133.750000
The Hunger Games Collection             4      490.00  122.500000
The Hobbit Collection                   3      750.00  250.000000
The Avengers Collection                 2      500.00  250.000000
The Lord of the Rings Collection        3      266.00   88.666667
X-Men Collection                        6      983.00  163.833333
Avatar Collection                       1      237.00  237.000000
Mission: Impossible Collection          5      650.00  130.000000
Spider-Man Collection                   3      597.00  199.000000
The Dark Knight Collection              3      585.00  195.000000

                                    revenue_musd              vote_average  \
                                             sum         mean         mean
belongs_to_collection
Harry Potter Collection              7707.367425   963.420928     7.537500
Star Wars Collection                 7434.494790   929.311849     7.375000
James Bond Collection                7106.970239   273.345009     6.338462
The Fast and the Furious Collection  5125.098793   640.637349     6.662500
Pirates of the Caribbean Collection  4521.576826   904.315365     6.880000
Transformers Collection              4366.101244   873.220249     6.140000
Despicable Me Collection             3691.070216   922.767554     6.783333
The Twilight Collection              3342.107290   668.421458     5.840000
Ice Age Collection                   3216.708553   643.341711     6.380000
Jurassic Park Collection             3031.484143   757.871036     6.500000
Shrek Collection                     2955.807008   738.951752     6.460000
The Hunger Games Collection          2944.162634   736.040659     6.875000
The Hobbit Collection                2935.523356   978.507785     7.233333
The Avengers Collection              2924.961604  1462.480802     7.350000
The Lord of the Rings Collection     2916.544743   972.181581     8.033333
X-Men Collection                     2808.832317   468.138720     6.816667
Avatar Collection                    2787.965087  2787.965087     7.200000
Mission: Impossible Collection       2778.977995   555.795599     6.600000
Spider-Man Collection                2496.346518   832.115506     6.466667
The Dark Knight Collection           2463.716216   821.238739     7.800000

                                           ROI    vote_count
                                        median          mean
belongs_to_collection
Harry Potter Collection               6.165086   5983.250000
Star Wars Collection                  8.239637   5430.375000
James Bond Collection                 6.128922   1284.307692
The Fast and the Furious Collection   4.942154   3197.000000
Pirates of the Caribbean Collection   3.453009   5016.000000
Transformers Collection               5.197167   3046.400000
Despicable Me Collection             12.761987   3041.333333
The Twilight Collection              10.271932   2770.200000
Ice Age Collection                    8.261760   2643.800000
Jurassic Park Collection              7.027789   4608.750000
Shrek Collection                      5.562873   2344.200000
The Hunger Games Collection           6.267722   6543.500000
The Hobbit Collection                 3.833600   5981.333333
The Avengers Collection               5.963190   9454.000000
The Lord of the Rings Collection     11.725157   8253.000000
X-Men Collection                      3.023632   4593.833333
Avatar Collection                    11.763566  12114.000000
Mission: Impossible Collection        4.548868   2801.000000
Spider-Man Collection                 3.918832   4505.666667
The Dark Knight Collection            4.339756   9681.000000

## Most Successful Directors

6. __Find__ the __most successful Directors__ in terms of

- __total number of movies__
- __total revenue__
- __mean rating__

In [47]:
movies.director.value_counts()

director
John Ford                  66
Michael Curtiz             65
Werner Herzog              54
Alfred Hitchcock           53
Georges Méliès             49
                           ..
Vladimir Mashkov            1
Pavel Ruminov               1
Gianfranco Mingozzi         1
Matthew Jason Walsh         1
Rokhsareh Ghaem Maghami     1
Name: count, Length: 17349, dtype: int64

In [48]:
directors = movies.groupby('director').agg({"title": "count", "budget_musd": ["sum", "mean"], "revenue_musd": ["sum", "mean"], "vote_average": "mean", "ROI": "median", "vote_count": "mean"})
directors

                    title budget_musd        revenue_musd            \
                    count         sum   mean          sum      mean
director
 Dale Trevillion\t      2        0.00    NaN     0.000000       NaN
 Davide Manuli          1        0.00    NaN     0.000000       NaN
 E.W. Swackhamer        1        0.00    NaN     0.000000       NaN
 Vitaliy Vorobyov       1        0.00    NaN     0.000000       NaN
 Yeon Sang-Ho           4        8.95  4.475     2.129768  2.129768
...                   ...         ...    ...          ...       ...
Ярополк Лапшин          1        0.00    NaN     0.000000       NaN
پیمان معادی             1        0.00    NaN     0.000000       NaN
塩谷 直義                   1        0.00    NaN     0.000000       NaN
杰森·莫玛                   1        0.00    NaN     0.000000       NaN
진모영                     1        0.00    NaN     0.000000       NaN

                    vote_average      ROI vote_count
                            mean   median       mean
director
 Dale Trevillion\t           4.0      NaN       2.00
 Davide Manuli               6.9      NaN      10.00
 E.W. Swackhamer             5.9      NaN       5.00
 Vitaliy Vorobyov            5.5      NaN       3.00
 Yeon Sang-Ho                6.6  0.24147     259.75
...                          ...      ...        ...
Ярополк Лапшин              10.0      NaN       1.00
پیمان معادی                  6.0      NaN       2.00
塩谷 直義                        7.2      NaN      40.00
杰森·莫玛                        5.8      NaN      28.00
진모영                          6.0      NaN       6.00

[17349 rows x 8 columns]